In [2]:
import numpy as np



In [3]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
np.linspace(1.1,10,10)

array([ 1.1       ,  2.08888889,  3.07777778,  4.06666667,  5.05555556,
        6.04444444,  7.03333333,  8.02222222,  9.01111111, 10.        ])

In [5]:
list1 = np.arange(1,11)
list2 = list1 * 3
list2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [29]:
mat = np.random.randint(0, 100, size=(2,5))
print(mat)
result = np.where(mat%2, mat, 0)
result = np.where(result==0, result, -1)
result



[[18  3 70  0 12]
 [81 54 50 36 51]]


array([[ 0, -1,  0,  0,  0],
       [-1,  0,  0,  0, -1]], dtype=int32)

In [30]:
import numpy as np

# 4x4 o'lchamdagi tasodifiy butun sonlardan iborat matritsa yaratish
np.random.seed(0)  # Tasodifiy natijalarni takrorlash uchun
arr = np.random.randint(0, 51, size=(4, 4))
print("Dastlabki matritsa:")
print(arr)

# Har bir qatorning yig'indisini hisoblash
row_sums = np.sum(arr, axis=1)
print("\nQatorlarning yig'indilari:")
print(row_sums)

# Yig'indi 100 dan katta bo'lgan qatorlarni 0 ga to'ldirish
arr[row_sums > 100] = 0

print("\nYakuniy matritsa:")
print(arr)

Dastlabki matritsa:
[[44 47  0  3]
 [ 3 39  9 19]
 [21 50 36 23]
 [ 6 24 24 12]]

Qatorlarning yig'indilari:
[ 94  70 130  66]

Yakuniy matritsa:
[[44 47  0  3]
 [ 3 39  9 19]
 [ 0  0  0  0]
 [ 6 24 24 12]]


In [48]:
arr = np.random.randint(0, 21, size=(5, 5))
print("1- Matritsa: \n")
print(arr)

row_sum = np.mean(arr, axis=0)
print("Qatorlar yig'indisi: \n")
print(row_sum)

arr[:, row_sum>10] = 1
arr[:, row_sum<10] = 0

print("Natija: \n")
print(arr)

1- Matritsa: 

[[20  7  3 12  3]
 [ 6 20  7 19  0]
 [ 5 11  9 19  7]
 [ 5  8 11 14  0]
 [ 8 19  6 10 19]]
Qatorlar yig'indisi: 

[ 8.8 13.   7.2 14.8  5.8]
Natija: 

[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


In [55]:
arr = np.random.randint(0, 31, size=(3, 6))
print("1- Matritsa: \n")
print(arr)

cool_mean = np.mean(arr, axis=0)
print("Qatorlar yig'indisi: \n")
print(cool_mean)

arr[:, cool_mean>15] = 1
arr[:, cool_mean<15] +=  5

print("Natija: \n")
print(arr)

1- Matritsa: 

[[24  1  0  5 24  2]
 [15  3 28 14  5 11]
 [19 24  6 20  6 28]]
Qatorlar yig'indisi: 

[19.33333333  9.33333333 11.33333333 13.         11.66666667 13.66666667]
Natija: 

[[ 1  6  5 10 29  7]
 [ 1  8 33 19 10 16]
 [ 1 29 11 25 11 33]]


In [61]:
arr = np.random.randint(1, 100, size=(10))
print(arr)
arr = np.sqrt(arr)
print(arr)
result = np.where(arr>5, arr, 1)
result = np.where(arr<5, arr, 0)
print(result)

[13 91 75 55 79 63 73 72 46  6]
[3.60555128 9.53939201 8.66025404 7.41619849 8.88819442 7.93725393
 8.54400375 8.48528137 6.78232998 2.44948974]
[3.60555128 0.         0.         0.         0.         0.
 0.         0.         0.         2.44948974]
