In [1]:
import numpy as np

In [4]:
arr = np.random.randint(20, size=(5, 5))
print(np.mean(arr))

8.64


In [6]:
arr = np.arange(1, 51)
n_arr = arr[arr % 3 == 0]
n_arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [7]:
arr = np.random.rand(4, 4)
np_arr = np.max(arr, axis=1)
print(arr)
print('')
print('')
print(np_arr)

[[0.99644423 0.19886384 0.46743676 0.93100357]
 [0.39329507 0.74467241 0.03114324 0.70209745]
 [0.08808607 0.10321004 0.01483833 0.37748342]
 [0.11666783 0.30959029 0.86219435 0.44248172]]


[0.99644423 0.74467241 0.37748342 0.86219435]


In [9]:
arr = np.random.randint(1, 100, 10)
n_arr = np.sqrt(arr)
n_arr

array([7.        , 1.        , 4.89897949, 8.1240384 , 9.38083152,
       6.40312424, 1.41421356, 8.54400375, 9.48683298, 9.69535971])