In [1]:
import numpy as np

In [5]:
arr = np.random.rand(3, 3)
print(arr) 
summ_arr = np.sum(arr, axis=0)
summ_arr

[[0.32891633 0.39681758 0.25914606]
 [0.45020604 0.20560322 0.6725442 ]
 [0.00117914 0.40442513 0.48032821]]


array([0.78030151, 1.00684593, 1.41201847])

In [8]:
import numpy as np

# 5x5 tasodifiy matritsa yaratamiz
mat = np.random.randint(1, 10, (5, 5))

print(mat)

# Diagonalni nolga o'zgartiramiz
np.fill_diagonal(mat, 0)

print('\n', mat)


[[7 5 8 1 9]
 [5 7 7 3 1]
 [6 8 8 3 3]
 [3 1 5 5 3]
 [7 1 5 7 4]]

 [[0 5 8 1 9]
 [5 0 7 3 1]
 [6 8 0 3 3]
 [3 1 5 0 3]
 [7 1 5 7 0]]
